---
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'traveltalkdb'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5435:5432'

  travel-talk-server:
    image: travel-talk-server:0.1
    build:
      dockerfile: ./Dockerfile
      context: ./
    profiles: [full]
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
    ports:
      - "8080:8080"
