server:
  port: 8080
spring:
  datasource:
    driver:
      class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5435/db
    username: postgres
#  liquibase:
#    change-log: classpath:db/travel-talk.yml
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
    show-sql: true

