---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
spec:
  selector:
    matchLabels:
      app: travel-talk-server
  template:
    metadata:
      labels:
        app: travel-talk-server
    spec:
      containers:
      - name: tomcat
        {{- if .Values.werf.image. }}
        image: {{ .Values.werf.image.app }}
        ports:
          - containerPort: 8080
            name: http
        env:
          - name: SERVER_PORT
            value: "8080"
          {{- with $.Values.env }}
          {{- if . }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.pgSecretName }}
                key: password
