---
{{- with $.Values.ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $.Release.Name }}-backend-server"
  metadata:
    {{- if .annotations }}
      {{- toYaml .annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .tls.enabled }}
  tls:
    - hosts:
        {{- $host := range .hosts }}
        - {{ $host }}
        {{- end }}
        secretName: "{{ $.Release.Name }}-tls"
  {{- end }}
  rules:
    {{- $host := range .hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Release.Name }}-svc"
                port:
                  name: http
    {{- end }}
{{- end }}
{{- end }}
