---
name: Build container image and update cluster deployment
on:
  push:
    branches:
      - main
      - ci-setup
jobs:
  deploy:
    name: "Deploy to kubernetes"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install keystone-auth
        run: |
          curl -sSL https://hub.mcs.mail.ru/repository/client-keystone-auth/latest/linux/client-install.sh | bash

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: "Deploy"
        run: |
          . $(werf ci-env github --as-file)
          cd .helm

          export PATH=$HOME/vk-cloud-solutions/bin:$PATH

          werf helm dependency update
          werf helm upgrade \
            --install \
            -n travel-talk-dev \
            --atomic \
            -f values.yaml \
            --timeout=15m0s \
            travel-talk-server .
        env:
          WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
